version: "2"
issues:
  new: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'SA1019: subscription.Message is deprecated: Prefer using TransportClient that is based on byte slices instead of this Message struct.'
      - path: (.+)\.go$
        text: 'SA1019: rand\.Seed.*'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/wundergraph)
        - prefix(github.com/wundergraph/graphql-go-tools)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
